# Generated by Django 5.0.3 on 2024-05-27 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtName', models.CharField(max_length=255)),
                ('opening', models.TimeField()),
                ('closing', models.TimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookingToggle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('imgRef', models.ImageField(upload_to='')),
                ('eventDescription', models.TextField()),
                ('showToggle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(max_length=255)),
                ('bookingToggle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userID', models.UUIDField(default=uuid.UUID('f6e154c8-a732-439d-9401-9efa335cf1dd'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_num', models.CharField(max_length=255)),
                ('accountType', models.CharField(choices=[('EXT', 'External'), ('STU', 'Student'), ('STA', 'Staff'), ('ADM', 'Admin')], default='EXT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.UUIDField(default=uuid.UUID('3bf1fd8f-b72a-499f-93e8-1bc1d8cb7a27'), primary_key=True, serialize=False)),
                ('bookTime', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booking')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.court')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidayName', models.CharField(max_length=255)),
                ('holidayDate', models.DateField()),
                ('venueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.venue')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='venueID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.venue'),
        ),
    ]
