# Generated by Django 5.0.3 on 2024-05-27 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.UUIDField(default=uuid.UUID('68167cc8-9d80-421f-b837-6ccaa802a10d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.UUIDField(default=uuid.UUID('55dd9510-3b93-47bb-9174-6ddd44f42428'), primary_key=True, serialize=False),
        ),
    ]
