# Generated by Django 5.0.3 on 2024-05-27 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_is_staff_alter_booking_bookingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.UUIDField(default=uuid.UUID('f4017a5a-3e72-48b7-a20f-b35295c5a2e7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.UUIDField(default=uuid.UUID('4940955e-7bd9-49ff-9d26-5b3e32528cb7'), primary_key=True, serialize=False),
        ),
    ]
