# Generated by Django 5.0.3 on 2024-05-27 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_booking_bookingid_alter_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingID',
            field=models.UUIDField(default=uuid.UUID('160aeb29-5f19-4a54-93ad-8ed5d4fe797f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.UUIDField(default=uuid.UUID('b33ba4be-3ac3-4cf8-aad4-bad74b3b3d06'), primary_key=True, serialize=False),
        ),
    ]
