# Generated by Django 4.2.13 on 2024-06-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imgRef',
            field=models.CharField(max_length=255),
        ),
    ]
